[package]
name = "cairo_project_template"
version = "0.1.0"

cairo-version = "2.5.3"
# Since we need to declare `starknet = "2.5.3"` in the dependencies list below,
# I'm not sure that declaring a `cairo-version` is useful, is it?

# Edition and Preludes
# Learn more here: https://community.starknet.io/t/cairo-v2-4-0-is-out/109275#editions-and-the-introduction-of-preludes-10
# and there: https://community.starknet.io/t/cairo-v2-5-0-is-out/112807#the-pub-keyword-9
# => UNCOMMENT BELOW LINE TO USE THE PRELUDE EDITION FOR CAIRO V2.5.0:
# edition = "2023_11"
#
# Previous editions were "2023_01" and "2023_10",
# respectively including all corelib base module, and lighter version.



[dependencies]
starknet = "2.5.3"
    # Check every Cairo release here -> https://github.com/starkware-libs/cairo/releases

# using sn forge v0.16.0 because v0.17.1 (latest version at creation of this boilerplate) triggers the following warning:
# "Package snforge_std version does not meet the recommended version requirement =0.16.0, it might result in unexpected behaviour".
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.16.0" }

# note that using OZ components from version 0.9.0 requires to use a cairo version >= 2.5.0
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.9.0" }



[[target.starknet-contract]]

# sn forge requires CASM code generation, which is disabled by default:
casm=true 

# Sierra contract class generation (required to declare contracts) is enabled by default.
# Switch to false to disable it:
# sierra=false





# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
